#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx3072M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

#App
app.name=Clipbird
app.packageName=com.srilakshmikanthanp.clipbird
app.description=A cross-platform clipboard sharing application
app.version=2.0.0
app.homepage=https://clipbird.srilakshmikanthanp.com/
app.sourcePage=https://github.com/srilakshmikanthanp/clipbird
app.issuesPage=https://github.com/srilakshmikanthanp/clipbird/issues
app.donatePage=https://donate.srilakshmikanthanp.com/
app.maintainerName=srilakshmikanthanp
app.maintainerEmail=srilakshmikanthanp@gmail.com

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
android.disallowKotlinSourceSets=false
