#pragma once

enum clipbird_advertiser_ble_error_code {
  CLIPBIRD_ADVERTISER_BLE_ALREADY_ADVERTISING = 1,
  CLIPBIRD_ADVERTISER_BLE_ADAPTER_NOT_FOUND = 2,
  CLIPBIRD_ADVERTISER_BLE_REGISTRATION_FAILED = 3
};
